spring:
  application:
    name: BookCrossingAPI
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    url: jdbc:postgresql://${SPRING_DATASOURCE_URL:localhost:5432}/${POSTGRES_DB_NAME:bookcrossing_api}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml