spring:
  application:
    name: BookCrossingAPI
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    password: ${POSTGRES_PASSWORD:postgres}
    username: ${POSTGRES_USER:postgres}
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost:5432}/${POSTGRES_DB_NAME:bookcrossing_api}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml